//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.02 at 07:56:39 PM PDT 
//


package https.soapservicecourse_com.courses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.soapservicecourse_com.courses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.soapservicecourse_com.courses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllCourseDetailResponse }
     * 
     */
    public GetAllCourseDetailResponse createGetAllCourseDetailResponse() {
        return new GetAllCourseDetailResponse();
    }

    /**
     * Create an instance of {@link CourseDetail }
     * 
     */
    public CourseDetail createCourseDetail() {
        return new CourseDetail();
    }

    /**
     * Create an instance of {@link DeleteCourseDetailResponse }
     * 
     */
    public DeleteCourseDetailResponse createDeleteCourseDetailResponse() {
        return new DeleteCourseDetailResponse();
    }

    /**
     * Create an instance of {@link DeleteCourseDetailRequest }
     * 
     */
    public DeleteCourseDetailRequest createDeleteCourseDetailRequest() {
        return new DeleteCourseDetailRequest();
    }

    /**
     * Create an instance of {@link GetAllCourseDetailRequest }
     * 
     */
    public GetAllCourseDetailRequest createGetAllCourseDetailRequest() {
        return new GetAllCourseDetailRequest();
    }

    /**
     * Create an instance of {@link GetCourseDetailResponse }
     * 
     */
    public GetCourseDetailResponse createGetCourseDetailResponse() {
        return new GetCourseDetailResponse();
    }

    /**
     * Create an instance of {@link GetCourseDetailRequest }
     * 
     */
    public GetCourseDetailRequest createGetCourseDetailRequest() {
        return new GetCourseDetailRequest();
    }

}
